[item]
guid = -HRLq14h5s8
title = "'We're very serious about human rights': Saudi minister on rights and the murder of Jamal Khashoggi"
description = "Saudi Minister of State for Foreign Affairs Adel Al-Jubeir says the kingdom's rulers are serious about human rights. "Mistakes happen," he said acknowledging the murder of Saudi journalist Jamal Khashoggi in Turkey."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=-HRLq14h5s8
category = "News & Politics"
pubdate = Sun, 17 Jul 2022 00:00:00 -0000
enclosure = -HRLq14h5s8.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/-HRLq14h5s8/maxresdefault.jpg

