[item]
guid = 00vGvrdY_nU
title = "It's impossible to work with the 5-Star Movement, says Forza Italia's Tajani"
description = "Antonio Tajani, national coordinator of Italy's Forza Italia party and member of European Parliament, discusses the 5-Star Movement's refusal to back Prime Minister Mario Draghi's national unity government in a parliamentary vote."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=00vGvrdY_nU
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = 00vGvrdY_nU.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/00vGvrdY_nU/hqdefault.jpg

