[item]
guid = 0MbXsIpQu7o
title = "President Biden is scheduled to touch down in Saudi Arabia later today"
description = "President Biden is scheduled to touch down in Saudi Arabia later today, CNBC's Hadley Gamble reports from Jeddah"
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=0MbXsIpQu7o
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = 0MbXsIpQu7o.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/0MbXsIpQu7o/maxresdefault.jpg

