[item]
guid = 0z0UUcswwik
title = "The U.S. and China are both important partners to Saudi Arabia, says Saudi's al-Jubeir"
description = "Adel al-Jubeir says Saudi Arabia's policy is to engage with different countries, including both the U.S. and China which are the kingdom's major partners. "We build bridges with people, we don't see one as exclusive of the other," the Saudi climate envoy told CNBC's Hadley Gamble."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=0z0UUcswwik
category = "News & Politics"
pubdate = Sat, 16 Jul 2022 00:00:00 -0000
enclosure = 0z0UUcswwik.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/0z0UUcswwik/maxresdefault.jpg

