[item]
guid = 1k-2NZNQ3dc
title = "Monetary policy can't really address most of current inflationary pressures: Macquarie Capital"
description = "Viktor Shvets of Macquarie Capital says that's because inflation isn't arising from excess demand but from disruptions to the goods and services market as well as the labor market."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=1k-2NZNQ3dc
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = 1k-2NZNQ3dc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/1k-2NZNQ3dc/maxresdefault.webp

