[item]
guid = 1k1OrITn_dY
title = "Japan's central bank is going to stay put for much longer: Financial services firm"
description = "Jesper Koll of Monex Group Japan discusses the Bank of Japan's decision to stick to its ultra-easy monetary policy, and says "all eyes are now on fiscal policy" to fight inflation."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=1k1OrITn_dY
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = 1k1OrITn_dY.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/1k1OrITn_dY/maxresdefault.jpg

