[item]
guid = 1u8HI8nZd3A
title = "Transparency is a 'huge problem' when it comes to sustainable investment, says Clarity AI CEO"
description = "Rebeca Minguela, founder and CEO of Clarity AI, says that's a challenge that applies not only to the climate crisis, but also to areas like diversity and other social issues."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=1u8HI8nZd3A
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = 1u8HI8nZd3A.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/1u8HI8nZd3A/maxresdefault.webp

