[item]
guid = 2kqD60utri4
title = "Currency depreciation is happening across Asia, says economist"
description = "Qian Wang of Vanguard says some central banks in Asia's emerging markets are accelerating monetary policy tightening partly because of currency depreciation."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=2kqD60utri4
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = 2kqD60utri4.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/2kqD60utri4/maxresdefault.jpg

