[item]
guid = 3OAuIIeLc2o
title = "Dan Yergin explains why crude prices are falling"
description = "Dan Yergin of S&P Global discusses how inflation and the risk of a recession are affecting oil prices."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=3OAuIIeLc2o
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = 3OAuIIeLc2o.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/3OAuIIeLc2o/hqdefault.jpg

