[item]
guid = 4-Khn2aWFLI
title = "'We're definitely in a difficult economic situation,' Sweden PM says"
description = "Sweden Prime Minister Magdalena Andersson tells CNBC that Europe is going through a difficult economic situation. Meanwhile, Latvia's Prime Minister Arturs Karins says Ukrainians are paying with their lives and Europe with its wallet."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=4-Khn2aWFLI
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = 4-Khn2aWFLI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/4-Khn2aWFLI/maxresdefault.jpg

