[item]
guid = 4ZZc9bgLa1A
title = "NATO sees Russia as a 'direct threat,' but not China, says think tank"
description = "Jim Townsend of the CNAS Transatlantic Security Program, who served as deputy assistant secretary of defense for Europe and NATO under the Obama administration, says Europe's view on China is more circumspect than what the U.S. might want it to be."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=4ZZc9bgLa1A
category = "News & Politics"
pubdate = Thu, 30 Jun 2022 00:00:00 -0000
enclosure = 4ZZc9bgLa1A.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/4ZZc9bgLa1A/hqdefault.jpg

