[item]
guid = 54Kjj2m_yNM
title = "Missteps and failures in crypto are inevitable, Tether co-founder says"
description = "Reeve Collins, CEO of BlockV and a co-founder of Tether, explains the difference between "algorithmic" stablecoins and those that are backed by reserves and provides his outlook for crypto regulation."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=54Kjj2m_yNM
category = "News & Politics"
pubdate = Mon, 27 Jun 2022 00:00:00 -0000
enclosure = 54Kjj2m_yNM.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/54Kjj2m_yNM/hqdefault.jpg

