[item]
guid = 5fsHK_6Rm2s
title = "U.S. delisting of Chinese firms is mostly a compliance issue on the China side, says academic"
description = "Winston Ma of the New York University School of Law says that because it's "fairly clear that the U.S. side does not want to change too much," it's up to China's side to figure out how to fully comply with U.S. regulatory requirements."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=5fsHK_6Rm2s
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = 5fsHK_6Rm2s.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/5fsHK_6Rm2s/maxresdefault.jpg

