[item]
guid = 5GqV5WpWeHI
title = "Bank of Cyprus governor says gradualism warranted as ECB normalizes monetary policy"
description = "Constantinos Herodotou, Governor of the Central Bank of Cyprus and Member of the ECB Governing Council, says inflation is likley to peak in the euro zone this year and shares his views on how the ECB should adapt its interest rate policy."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=5GqV5WpWeHI
category = "News & Politics"
pubdate = Wed, 29 Jun 2022 00:00:00 -0000
enclosure = 5GqV5WpWeHI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/5GqV5WpWeHI/hqdefault.jpg

