[item]
guid = 7BlP9ki_7_8
title = "Not clear that monkeypox is confined to gay and bisexual groups, says WHO"
description = "Dr. Catherine Smallwood, senior emergency officer at the World Health Organization, says there is little evidence to suggest that monkeypox will remain confined to communities of gay and bisexual men, who have thus far suffered the brunt of the outbreak."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=7BlP9ki_7_8
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = 7BlP9ki_7_8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/7BlP9ki_7_8/maxresdefault.webp

