[item]
guid = 7CWA9WzXufU
title = "Curtailing inflation is the most important thing for Sri Lanka's economy, says central bank governor"
description = "Nandalal Weerasinghe, governor of the Central Bank of Sri Lanka, says inflation in the country could peak in the next couple of months and discusses how its controlling inflation expectations going forward."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=7CWA9WzXufU
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = 7CWA9WzXufU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/7CWA9WzXufU/sddefault.jpg

