[item]
guid = 7E7Re8dzjg8
title = "Sri Lanka crisis: There has to be understanding between international creditors, says researcher"
description = "C. Raja Mohan of the Institute of South Asian Studies discusses Sri Lanka's economic crisis. He says "there has to be some understanding between the international creditors and the international institutions to support [the country's] path to recovery.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=7E7Re8dzjg8
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = 7E7Re8dzjg8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/7E7Re8dzjg8/hqdefault.jpg

