[item]
guid = 7HN4evrJ7Hc
title = "EU very much likes to have Draghi leading Italy, official says amid new political uncertainty"
description = "EU Commissioner for Economic Affairs Paolo Gentiloni talks to CNBC about Italy's latest political uncertainty and the country's economy."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=7HN4evrJ7Hc
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = 7HN4evrJ7Hc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/7HN4evrJ7Hc/maxresdefault.jpg

