[item]
guid = 88vFN6f6Lj0
title = "Biden administration needs to treat Saudi Arabia 'with respect,' says former U.S. energy secretary"
description = "Former U.S. Energy Secretary Dan Brouillette joins CNBC’s "Capital Connection" to discuss President Biden's trip to Saudi Arabia."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=88vFN6f6Lj0
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = 88vFN6f6Lj0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/88vFN6f6Lj0/hqdefault.jpg

