[item]
guid = 9--tck_tVxE
title = "China may not continue spending a large amount of money on its Belt and Road Initiative: Think tank"
description = "Creon Butler of Chatham House says China is unlikely to continue with its current level of spending as the country has been "burnt in a number of ways" by its debt issues."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=9--tck_tVxE
category = "News & Politics"
pubdate = Mon, 27 Jun 2022 00:00:00 -0000
enclosure = 9--tck_tVxE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/9--tck_tVxE/hqdefault.jpg

