[item]
guid = 9A7AhxhQ5CA
title = "'Don't get too sucked back in': Fund manager discusses what past bear markets can teach us"
description = "Trevor Greetham, head of multi-asset at Royal London Asset Management, discusses historical bear markets and says there could be a "long, grinding period" ahead for stock markets."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=9A7AhxhQ5CA
category = "News & Politics"
pubdate = Mon, 27 Jun 2022 00:00:00 -0000
enclosure = 9A7AhxhQ5CA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/9A7AhxhQ5CA/maxresdefault.webp

