[item]
guid = 9gEt86h1XrY
title = "SAP CEO: Tech investment pipeline 'very robust'"
description = "Christian Klein, CEO at SAP, discusses the company's Q2 figures and impact of Europe's macroeconomic and geopolitical environment on the company."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=9gEt86h1XrY
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = 9gEt86h1XrY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/9gEt86h1XrY/maxresdefault.webp

