[item]
guid = _38J0_L1amE
title = "'There are alternatives to Russian oil,' OECD chief says of U.S. call for a Russian oil price cap"
description = "Mathias Cormann, secretary-general of the Organization for Economic Cooperation and Development, responds to a question about U.S. Treasury Secretary Janet Yellen's proposal of a price cap on Russian oil."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=_38J0_L1amE
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = _38J0_L1amE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/_38J0_L1amE/hqdefault.jpg

