[item]
guid = acbEOW_7fNQ
title = "JPMorgan explains why it likes Chinese tech stocks"
description = "Alexander Treves of JPMorgan Asset Management discusses why that's the case even though the company is underweight on China A-shares."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=acbEOW_7fNQ
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = acbEOW_7fNQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/acbEOW_7fNQ/maxresdefault.webp

