[item]
guid = aLcXa-tqgc0
title = "Prince Turki: President Biden is coming to Saudi as 'a much diminished president'"
description = "Prince Turki Al-Faisal, Saudi Arabia’s former intelligence chief and former ambassador to the United States, says President Joe Biden is coming to Saudi Arabia as “a much diminished president.”"
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=aLcXa-tqgc0
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = aLcXa-tqgc0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/aLcXa-tqgc0/hqdefault.jpg

