[item]
guid = ANyNOW9aFMM
title = "Gas prices will remain high after Nord Stream 1 resumption, economist says"
description = "Eric Heymann, senior economist at Deutsche Bank Research, discusses Russia's decision to resume gas supply to Europe after 10 days of maintenance."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=ANyNOW9aFMM
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = ANyNOW9aFMM.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ANyNOW9aFMM/maxresdefault.jpg

