[item]
guid = aqxV5Jneer4
title = "UBS discusses the outlook for the dollar-yuan"
description = "Tan Teck Leng of UBS Global Wealth Management explains why it's "a little bit worried" about near-term sentiment."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=aqxV5Jneer4
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = aqxV5Jneer4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/aqxV5Jneer4/maxresdefault.jpg

