[item]
guid = aW34W1DpUUc
title = "Stephen Roach says China's economy is set for a weak rebound"
description = "Stephen Roach of Yale University says China's weak recovery makes it vulnerable to another shock, such as more Covid lockdowns and "any one of a number of possibilities that we can't even imagine right now.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=aW34W1DpUUc
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = aW34W1DpUUc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/aW34W1DpUUc/maxresdefault.jpg

