[item]
guid = b9x9uk7lMg0
title = "Fed's Mester says market volatility is probably here to stay"
description = "Cleveland Fed President Loretta Mester tells CNBC's Annette Weisbach about the likely outcome of the Federal Reserve's July meeting and gives her outlook on inflation and its impacts on the economy."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=b9x9uk7lMg0
category = "News & Politics"
pubdate = Wed, 29 Jun 2022 00:00:00 -0000
enclosure = b9x9uk7lMg0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/b9x9uk7lMg0/maxresdefault.jpg

