[item]
guid = BDNIiNMae2o
title = "China's economic recovery is going to be 'very slow,' says asset management firm"
description = "David Loevinger of the TCW Group says the uncertainty will linger as long as the country's zero-Covid policy remains."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=BDNIiNMae2o
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = BDNIiNMae2o.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/BDNIiNMae2o/maxresdefault.jpg

