[item]
guid = BGUhw8XQxPA
title = "Crypto hedge fund Three Arrows Capital plunges into liquidation. This is how it happened"
description = "Crypto hedge fund Three Arrows Capital has fallen into liquidation. The company is yet another victim of the plunge in cryptocurrency prices which has exposed its highly leveraged bets. CNBC's Arjun Kharpal reports on how 3AC got here."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=BGUhw8XQxPA
category = "News & Politics"
pubdate = Thu, 30 Jun 2022 00:00:00 -0000
enclosure = BGUhw8XQxPA.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/BGUhw8XQxPA/maxresdefault.jpg

