[item]
guid = d1R0CHwwFjw
title = "Stock markets 'didn't puke' on the latest U.S. inflation print, investor says"
description = "Ben Gutteridge, director of model portfolio services at Invesco, says the stock market reaction has been "relatively benign" so far."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=d1R0CHwwFjw
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = d1R0CHwwFjw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/d1R0CHwwFjw/maxresdefault.webp

