[item]
guid = d9BWNoplAr0
title = "President of Kosovo: We deserve to be in EU"
description = "President of Kosovo Vjosa Osmani-Sadriu tells CNBC's Silvia Amaro why her country is pushing to join the EU, and how she perceives the bloc has dealt with the invasion of Ukraine."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=d9BWNoplAr0
category = "News & Politics"
pubdate = Thu, 23 Jun 2022 00:00:00 -0000
enclosure = d9BWNoplAr0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/d9BWNoplAr0/maxresdefault.webp

