[item]
guid = DCoLOzuj_o8
title = "China remains world's largest e-sport market despite gaming crackdown, says Niko Partners"
description = "China's e-sports revenue totaled $403.1 million in 2021, making it the largest single market in the world, according to Niko Partners. Alexander Champlin, head of e-sports at Niko Partners, discusses whether China's stricter gaming regulation could affect the industry."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=DCoLOzuj_o8
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = DCoLOzuj_o8.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/DCoLOzuj_o8/maxresdefault.jpg

