[item]
guid = dkCwxXxFeQ8
title = "Inflation risks in Singapore will 'certainly be tackled,' says Mizuho Bank"
description = "Vishnu Varathan of the bank says the Monetary Authority of Singapore has "done a lot more [monetary policy] tightening upfront," giving it much more flexibility."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=dkCwxXxFeQ8
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = dkCwxXxFeQ8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/dkCwxXxFeQ8/maxresdefault.jpg

