[item]
guid = DTpgXhUx74k
title = "Expect more volatility in China's property market, says real estate firm"
description = "Henry Chin of CBRE Group discusses the outlook for China's property market, and says "any relaxation for the wider industry is super, super unlikely to happen.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=DTpgXhUx74k
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = DTpgXhUx74k.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/DTpgXhUx74k/hqdefault.jpg

