[item]
guid = DTuBkZfcmco
title = "Saudi Arabia is committed to stabilizing international oil markets, its climate envoy says"
description = "Saudi Arabia's climate envoy Adel al-Jubeir says his country is committed to ensuring that markets are adequately supplied with crude oil, and will consult with OPEC+ on whether there's a need to bring more oil on to the markets."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=DTuBkZfcmco
category = "News & Politics"
pubdate = Sat, 16 Jul 2022 00:00:00 -0000
enclosure = DTuBkZfcmco.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/DTuBkZfcmco/maxresdefault.webp

