[item]
guid = duHTNTldg1s
title = "Sri Lanka: Political maneuvering behind the scenes is the 'fly in the ointment,' says think tank"
description = "Ganeshan Wignaraja of ODI Global discusses what President Gotabaya Rajapaksa's resignation might mean for the country's future."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=duHTNTldg1s
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = duHTNTldg1s.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/duHTNTldg1s/maxresdefault.jpg

