[item]
guid = DyQI-S39KUQ
title = "Dan Yergin on Biden's trip to Saudi Arabia: 'Oil is on his mind'"
description = "S&P Global’s Dan Yergin joins CNBC's "Capital Connection" to discuss President Joe Biden's trip to Saudi Arabia."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=DyQI-S39KUQ
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = DyQI-S39KUQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/DyQI-S39KUQ/hqdefault.jpg

