[item]
guid = fG3eWXcTnyg
title = "No one is talking about millennials' role in high inflation, investor says"
description = "A root cause of inflation is too many people chasing too few goods, and those people now are millions of millennials who are finally purchasing assets, says Bill Smead, CIO at Smead Capital Management."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=fG3eWXcTnyg
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = fG3eWXcTnyg.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/fG3eWXcTnyg/maxresdefault.jpg

