[item]
guid = FKqOx9C6GQ4
title = "Biden needs to strike a delicate balance with China, says JPMorgan"
description = "Tai Hui of JPMorgan Asset Management says U.S. president Joe Biden will have to do a very "delicate calculation" on how to get the maximum benefit from rolling back on China tariffs to reduce headline inflation, but at the same time play tough on China."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=FKqOx9C6GQ4
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = FKqOx9C6GQ4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/FKqOx9C6GQ4/maxresdefault.webp

