[item]
guid = fKQphD6Ss7Q
title = "China faces many challenges in achieving its full-year economic targets, says statistics bureau"
description = "However, a spokesperson for the National Bureau of Statistics of China said the country is performing better than the U.S. and Europe when it comes to inflation. CNBC's Evelyn Cheng reports."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=fKQphD6Ss7Q
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = fKQphD6Ss7Q.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/fKQphD6Ss7Q/maxresdefault.jpg

