[item]
guid = fMO50iJVfJg
title = "EU not yet ready to propose an oil price cut, official says"
description = "European Commissioner Paolo Gentiloni comments on the prospects of an oil price cap as suggested by the United States."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=fMO50iJVfJg
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = fMO50iJVfJg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/fMO50iJVfJg/hqdefault.jpg

