[item]
guid = FqBEoje7trU
title = "'The glass is half full and half empty': Economist weighs in on Thailand's economic outlook"
description = "Louis Kuijs of S&P Global Ratings discusses the global headwinds and domestic developments that are affecting the Thai economy."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=FqBEoje7trU
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = FqBEoje7trU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/FqBEoje7trU/maxresdefault.webp

