[item]
guid = FYrXJ-_HtnA
title = "This 'crypto winter' is different from the last. Here's why"
description = "Cryptocurrency prices have crashed in the last few months as the industry enters a new "crypto winter." Crypto has seen this before, most recently in 2018. But things are different this time. CNBC's Arjun Kharpal reports on the factors that have driven the price plunge in the most recent crypto cycle."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=FYrXJ-_HtnA
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = FYrXJ-_HtnA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/FYrXJ-_HtnA/maxresdefault.jpg

