[item]
guid = G3wk7UPx1DI
title = "Inflation is unacceptably high and bringing it down should be the top priority, says Janet Yellen"
description = "Speaking ahead of the Group of 20 finance ministers' meeting in Bali, U.S. Treasury Secretary Janet Yellen says the Department of the Treasury is taking its own steps to cool inflation in the short term, while being supportive of the Federal Reserve's efforts."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=G3wk7UPx1DI
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = G3wk7UPx1DI.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/G3wk7UPx1DI/hqdefault.jpg

