[item]
guid = G5NUO_MJnFA
title = "ECB's Herodotou sees euro zone inflation peaking this year"
description = "Constantinos Herodotou, Governor of the Central Bank of Cyprus and Member of the ECB Governing Council, speaks to CNBC's Annette Weisbach about negotiations for a euro zone fragmentation tool, and lays out his inflation predictions."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=G5NUO_MJnFA
category = "News & Politics"
pubdate = Wed, 29 Jun 2022 00:00:00 -0000
enclosure = G5NUO_MJnFA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/G5NUO_MJnFA/hqdefault.jpg

