[item]
guid = GLO7WCr0bP0
title = "Sri Lanka is on the verge of becoming a 'fragile state,' says professor"
description = "Shanta Devarajan of Georgetown University discusses Sri Lanka’s debt crisis."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=GLO7WCr0bP0
category = "News & Politics"
pubdate = Thu, 30 Jun 2022 00:00:00 -0000
enclosure = GLO7WCr0bP0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/GLO7WCr0bP0/maxresdefault.webp

