[item]
guid = HcHs80WPX_I
title = "Barings: Margins, not topline results, are the focus for this earnings season"
description = "Christopher Smart of Barings says that higher costs can squeeze margins and dampen outlook, but consumer spending and job markets still indicate a strong economy and moderate earnings growth."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=HcHs80WPX_I
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = HcHs80WPX_I.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/HcHs80WPX_I/maxresdefault.jpg

