[item]
guid = hgW59fows_s
title = "Philippine liquor company says its expansion plans are not limited to Asia-Pacific"
description = "Bryan Donaghey, head of business at Emperador and CEO of Emperador-owned Whyte & Mackay, discusses its secondary listing on the Singapore Exchange and its international expansion plans."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=hgW59fows_s
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = hgW59fows_s.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/hgW59fows_s/maxresdefault.jpg

