[item]
guid = HpARGpWYInU
title = "Saudi Arabia is going to be a major player in hydrogen, says former U.S. energy secretary"
description = "Dan Brouillette, who served as the U.S. secretary of energy from 2019 to 2021, says he hopes U.S. President Joe Biden will, during his visit to Saudi Arabia, raise questions that go beyond oil production, such as how the country's hydrogen market can be developed."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=HpARGpWYInU
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = HpARGpWYInU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/HpARGpWYInU/maxresdefault.jpg

