[item]
guid = iaCSpjvhe6g
title = "CEO of food and agriculture firm explains why it's continuing operations in Russia"
description = "Sunny Verghese, CEO of Olam Group, says it strives for "food security for all.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=iaCSpjvhe6g
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = iaCSpjvhe6g.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/iaCSpjvhe6g/hqdefault.jpg

