[item]
guid = ixUH3igLR9Q
title = "India continues to produce the most talent in the tech industry, says IT firm Wipro"
description = "Thierry Delaporte of the IT services firm says the company has been vigilant in ensuring it hires outstanding talent."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=ixUH3igLR9Q
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = ixUH3igLR9Q.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/ixUH3igLR9Q/maxresdefault.jpg

