[item]
guid = JeyUCVa6FUo
title = "Strategist says investors are quickly running out of safe assets as recession risks grow"
description = "Michael Howell, managing director at CrossBorder Capital, discusses the outlook for the euro/dollar currency pair and his views on so-called safe-haven assets as recession risks intensify."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=JeyUCVa6FUo
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = JeyUCVa6FUo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/JeyUCVa6FUo/maxresdefault.webp

