[item]
guid = JgcoVCjYiIE
title = "Futu Singapore says it is looking to expand in Southeast Asia"
description = "Gavin Chia of the wealth management platform discusses its expansion plans and how it educates clients about investments."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=JgcoVCjYiIE
category = "News & Politics"
pubdate = Thu, 30 Jun 2022 00:00:00 -0000
enclosure = JgcoVCjYiIE.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/JgcoVCjYiIE/maxresdefault.jpg

