[item]
guid = Jl1H-uDV8EY
title = "Remains to be seen when Sri Lanka's state of emergency will be lifted, says bar association"
description = "Saliya Pieris of the Bar Association of Sri Lanka says this is the third time a state of emergency has been declared."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=Jl1H-uDV8EY
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = Jl1H-uDV8EY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Jl1H-uDV8EY/maxresdefault.jpg

