[item]
guid = jLSjTUnpAIc
title = "Thai crypto exchange urges caution on investing in the market"
description = "Jirayut "Topp" Srupsrisopa, CEO of Bitkub, says there's usually a "golden year" for the industry every four years, but "we have already passed the golden year in 2021.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=jLSjTUnpAIc
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = jLSjTUnpAIc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/jLSjTUnpAIc/maxresdefault.webp

