[item]
guid = JRAY-URXUR0
title = "Israel wants Biden to reaffirm his commitment to the country's security, says ex-U.S. diplomat"
description = "Marc Ginsberg, former U.S. Ambassador to Morocco, discusses U.S. President Joe Biden's trip to Israel and what he thinks Israelis want the most from his visit."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=JRAY-URXUR0
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = JRAY-URXUR0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/JRAY-URXUR0/maxresdefault.jpg

