[item]
guid = k1BeRV_6-C0
title = "Bernstein analyst likes these two airlines despite travel chaos"
description = "Alexander Irving, European transport analyst at AB Bernstein, discusses which airlines are best suited to weather the travel chaos and staff shortages plaguing a number of large airports across the region."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=k1BeRV_6-C0
category = "News & Politics"
pubdate = Mon, 27 Jun 2022 00:00:00 -0000
enclosure = k1BeRV_6-C0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/k1BeRV_6-C0/hqdefault.jpg

