[item]
guid = khf6RrEAxnA
title = "Biden's visit to Saudi Arabia was a difficult one, says former U.S. diplomat"
description = "William Roebuck, executive vice president at the Arab Gulf States Institute in Washington, formerly U.S. ambassador to Bahrain, discusses the criticism surrounding President Joe Biden's trip to the Middle East."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=khf6RrEAxnA
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = khf6RrEAxnA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/khf6RrEAxnA/hqdefault.jpg

