[item]
guid = KT6IBDxyzQw
title = "G-7 has to prepare for a gas shutdown as energy crisis continues, says think tank"
description = "Jeffrey Schott of the Peterson Institute for International Economics says Europe is in a very tight situation and is playing for time."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=KT6IBDxyzQw
category = "News & Politics"
pubdate = Mon, 27 Jun 2022 00:00:00 -0000
enclosure = KT6IBDxyzQw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/KT6IBDxyzQw/maxresdefault.webp

