[item]
guid = lcD5Y32Lf2g
title = "Wood Mackenzie says it expects further cuts to Europe's gas supply"
description = "Massimo Di Odoardo of Wood Mackenzie discusses how markets are reflecting the outlook for Europe's energy crisis."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=lcD5Y32Lf2g
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = lcD5Y32Lf2g.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/lcD5Y32Lf2g/hqdefault.jpg

