[item]
guid = LL1w6PnTuTg
title = "Indonesia's GoTo discusses what it needs to achieve its sustainability goals"
description = "Tanah Sullivan of the company says there are "serious blood, sweat and tears" that have gone into helping it achieve its goals by 2030."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=LL1w6PnTuTg
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = LL1w6PnTuTg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/LL1w6PnTuTg/maxresdefault.webp

