[item]
guid = mA1bqddsSy8
title = "German government's support package for Uniper is 'absolutely necessary,' says analyst"
description = "Nikoline Bromander, Gas and LNG analyst at Rystad Energy, discusses Uniper's government bailout and outlook for Europe's energy market."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=mA1bqddsSy8
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = mA1bqddsSy8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/mA1bqddsSy8/hqdefault.jpg

