[item]
guid = MLT2kwkFkMM
title = "The European Central Bank started hiking rates too late, says futures brokerage company"
description = "Marc Ostwald of ADM Investor Services International discusses the challenge that the ECB faces in balancing "two very conflicting interests.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=MLT2kwkFkMM
category = "News & Politics"
pubdate = Thu, 30 Jun 2022 00:00:00 -0000
enclosure = MLT2kwkFkMM.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/MLT2kwkFkMM/hqdefault.jpg

