[item]
guid = MojM6gd6OAY
title = "Reversal of Roe v. Wade is a 'business risk' for the United States, says geopolitical strategist"
description = "Tina Fordham, founder of Fordham Global Foresight, discusses the overturning of Roe v. Wade and says there is disbelief on the part of U.S. allies over the reversal of what's seen as a fundamental right."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=MojM6gd6OAY
category = "News & Politics"
pubdate = Mon, 27 Jun 2022 00:00:00 -0000
enclosure = MojM6gd6OAY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/MojM6gd6OAY/hqdefault.jpg

