[item]
guid = My8aBGW1bI4
title = "Protests in Sri Lanka are moving to a different stage, says think tank"
description = "Asanga Abeyagoonasekera of the Millennium Project says there's been a "thorough breach of the social contract" between the public and its rulers, adding that the "trust deficit" is widening."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=My8aBGW1bI4
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = My8aBGW1bI4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/My8aBGW1bI4/maxresdefault.webp

