[item]
guid = N02unPZLduc
title = "Commodities rout pointing to recession fears, says analyst"
description = "Ole Hansen, head of commodity strategy at Saxo Bank, weighs in on U.S. President Biden's gas tax plans, his outlook for oil prices, and what the commodities sector can tell us about a potential recession."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=N02unPZLduc
category = "News & Politics"
pubdate = Thu, 23 Jun 2022 00:00:00 -0000
enclosure = N02unPZLduc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/N02unPZLduc/maxresdefault.jpg

