[item]
guid = n3T1BDohViI
title = "Escalation of war in Ukraine means 'we all pay the price,' says Saudi minister al-Jubeir"
description = "Adel al-Jubeir, Saudi Arabia's minister of state for foreign affairs, says things could spin out of control if there's an escalation in the Russia-Ukraine war — as can already be seen in disruptions in energy markets, refugee crisis and food supply."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=n3T1BDohViI
category = "News & Politics"
pubdate = Sun, 17 Jul 2022 00:00:00 -0000
enclosure = n3T1BDohViI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/n3T1BDohViI/maxresdefault.webp

