[item]
guid = ncExXABcSL4
title = "Asian central banks are being vigilant on inflation, ADB says"
description = "Albert Park of the bank says although the reliance on rice as opposed to wheat or corn in Asia has managed to keep inflation in check, he discusses the factors that could lead to the increase in rice prices."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=ncExXABcSL4
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = ncExXABcSL4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ncExXABcSL4/hqdefault.jpg

