[item]
guid = nEBuS6Fu0Ks
title = "Emissions 'don't have a passport': IEA's Birol talks clean energy, climate change and price caps"
description = "Fatih Birol, the executive director of the International Energy Agency, discusses clean energy, the climate crisis and price caps."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=nEBuS6Fu0Ks
category = "News & Politics"
pubdate = Mon, 27 Jun 2022 00:00:00 -0000
enclosure = nEBuS6Fu0Ks.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/nEBuS6Fu0Ks/hqdefault.jpg

