[item]
guid = neEjmbLZHh8
title = "Clues on profitability will be ‘absolutely crucial’ this earnings season, Julius Baer CIO says"
description = "Yves Bonzon, group CIO at Julius Baer, discusses expectations for the second-quarter earnings season and liquidity in the market."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=neEjmbLZHh8
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = neEjmbLZHh8.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/neEjmbLZHh8/maxresdefault.jpg

