[item]
guid = NfDeGb3m1Yo
title = "Nearly 70% of respondents say sustainability will be an important growth factor, survey finds"
description = "John Goddard, vice chair of sustainability at L.E.K Consulting, discusses the results of its survey, which he says has yielded insights on "how corporations are embedding sustainability into the business.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=NfDeGb3m1Yo
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = NfDeGb3m1Yo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/NfDeGb3m1Yo/hqdefault.jpg

