[item]
guid = nmhtftirct0
title = "Full Interview: Presiden Indonesia Joko Widodo mengenai Warisan, G20, Elon Musk dan lain-lain"
description = "Subscribe to CNBC International TV: http://cnb.cx/2wAkfMv\n \nSubscribe to CNBC International: http://cnb.cx/2gft82z\n\nLike our Facebook page\nhttps://www.facebook.com/cnbcinternational\n\nFollow us on Instagram\nhttps://www.instagram.com/cnbcinternational/\n\nFollow us on Twitter\nhttps://twitter.com/cnbci"
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=nmhtftirct0
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = nmhtftirct0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/nmhtftirct0/maxresdefault.webp

