[item]
guid = nsq6-4NfwKc
title = "The speed at which Japan's yen has weakened warrants government intervention, analyst says"
description = "Takuji Okubo of Japan Macro Advisors says the yen is at very low levels and there's excessive volatility in the exchange rate."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=nsq6-4NfwKc
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = nsq6-4NfwKc.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/nsq6-4NfwKc/maxresdefault.jpg

