[item]
guid = nzKzF4QYGCM
title = "Tory leadership contenders aren't trying to pitch to the general British population, says professor"
description = "Tony Travers of the London School of Economics and Political Science discusses Britain's Conservative leadership race."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=nzKzF4QYGCM
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = nzKzF4QYGCM.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/nzKzF4QYGCM/maxresdefault.jpg

