[item]
guid = OA9GlVuMLjM
title = "The central bank is the Achilles' heel for Sri Lanka and most developing countries, says professor"
description = "Steven Hanke of Johns Hopkins University says that's because the central bank can extend credit to the government, and that "imposes no discipline on the fiscal authorities.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=OA9GlVuMLjM
category = "News & Politics"
pubdate = Tue, 26 Jul 2022 00:00:00 -0000
enclosure = OA9GlVuMLjM.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/OA9GlVuMLjM/maxresdefault.jpg

