[item]
guid = OMBXp4qOOqA
title = "Question of spare oil capacity will be on Biden's mind during his Middle East trip, says Dan Yergin"
description = "Dan Yergin of S&P Global says Iran, Russia and China are also on U.S. President Joe Biden's agenda for his visit."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=OMBXp4qOOqA
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = OMBXp4qOOqA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/OMBXp4qOOqA/maxresdefault.jpg

