[item]
guid = oPdZ3nQ1HI4
title = "IFO: Europe energy will face chllenges in winter when heating is needed"
description = "Clemens Fuest, president of the IFO Institute, talks to CNBC's Julianna Tatelbaum."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=oPdZ3nQ1HI4
category = "News & Politics"
pubdate = Sat, 25 Jun 2022 00:00:00 -0000
enclosure = oPdZ3nQ1HI4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/oPdZ3nQ1HI4/maxresdefault.jpg

