[item]
guid = OQXnr6-Ye_8
title = "Singapore's inflation will likely be 'quite sustained' in the second half of 2022, says Barclays"
description = "Brian Tan of the bank says Singapore's economy is "definitely operating above its potential.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=OQXnr6-Ye_8
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = OQXnr6-Ye_8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/OQXnr6-Ye_8/hqdefault.jpg

