[item]
guid = ORSwpLOPJuU
title = "Shell CEO says OPEC probably doesn't have as much spare capacity of oil as many people think"
description = "Ben van Beurden, CEO of the energy company, says an "ever tighter" oil and gas market is appearing."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=ORSwpLOPJuU
category = "News & Politics"
pubdate = Thu, 30 Jun 2022 00:00:00 -0000
enclosure = ORSwpLOPJuU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ORSwpLOPJuU/maxresdefault.jpg

