[item]
guid = oxEXhqUQe7k
title = "Bad news is good news for markets right now, portfolio manager says"
description = "Florian Ielpo, head of Macro and Multi-Asset Portfolio Manager at Lombard Odier Investment, discusses the rise in risk aversion in global markets."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=oxEXhqUQe7k
category = "News & Politics"
pubdate = Thu, 30 Jun 2022 00:00:00 -0000
enclosure = oxEXhqUQe7k.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/oxEXhqUQe7k/maxresdefault.webp

