[item]
guid = PI8WfRWJHAA
title = "Accenture strategist names 3 factors that are damaging business confidence"
description = "Rachel Barton of Accenture discusses the results of an Accenture/S&P survey."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=PI8WfRWJHAA
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = PI8WfRWJHAA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/PI8WfRWJHAA/maxresdefault.webp

