[item]
guid = PpOMvzKOlqc
title = "Southeast Asia looks 'pretty good' in the face of rising interest rates, says Asian Development Bank"
description = "Ahmed Saeed of the regional development bank says there's always a risk, as U.S. interest rates rise, that when it sneezes, the world catches a cold, but Southeast Asian economies have been taking their vitamins. He was speaking on the sidelines of the Group of 20 meeting of financial leaders in Bali."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=PpOMvzKOlqc
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = PpOMvzKOlqc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/PpOMvzKOlqc/sddefault.jpg

