[item]
guid = Qc5TRdb1GYw
title = "China's mortgage boycott will have a small effect on banks, says analyst"
description = "Iris Tan of Morningstar discusses reports of an increasing number of homebuyers across China who are refusing to repay mortgage loans for delayed projects."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=Qc5TRdb1GYw
category = "News & Politics"
pubdate = Tue, 26 Jul 2022 00:00:00 -0000
enclosure = Qc5TRdb1GYw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/Qc5TRdb1GYw/maxresdefault.webp

