[item]
guid = qHe4EKDeLJ8
title = "VistaJet chief: Electric planes are decades away"
description = "In conversation with CNBC's Dan Murphy, Thomas Flohr, the founder and CEO of private jet subscription service VistaJet, discussed his company's carbon neutral commitment and why he doesn't think we'll see the electrification of the aviation industry anytime soon."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=qHe4EKDeLJ8
category = "News & Politics"
pubdate = Wed, 29 Jun 2022 00:00:00 -0000
enclosure = qHe4EKDeLJ8.mp4

[item "itunes"]
image = https://i.ytimg.com/vi_webp/qHe4EKDeLJ8/maxresdefault.webp

