[item]
guid = qMdKA6oMmGg
title = "The Bank of Japan is right to stick to its own philosophy: Economist"
description = "Kazuo Momma of Mizuho Research & Technologies explains why there's no reason for the Bank of Japan to shift its monetary policy in the current situation."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=qMdKA6oMmGg
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = qMdKA6oMmGg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/qMdKA6oMmGg/hqdefault.jpg

