[item]
guid = Qrja7jCV-jI
title = "Jordan finance minister: Jordan will be resilient to economic shocks"
description = "Mohamad Al-Ississ, finance minister of Jordan, speaks exclusively to CNBC's Hadley Gamble."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=Qrja7jCV-jI
category = "News & Politics"
pubdate = Sat, 25 Jun 2022 00:00:00 -0000
enclosure = Qrja7jCV-jI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Qrja7jCV-jI/hqdefault.jpg

