[item]
guid = qXRxvWpLnXg
title = "Biden's Middle East trip is 'quite questionable,' says think tank"
description = "Trita Parsi of The Quincy Institute says that when it comes to reasserting American leadership, there's likely to be "more rhetoric than substance.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=qXRxvWpLnXg
category = "News & Politics"
pubdate = Thu, 14 Jul 2022 00:00:00 -0000
enclosure = qXRxvWpLnXg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/qXRxvWpLnXg/maxresdefault.jpg

