[item]
guid = QYxop4AEhCY
title = "Market will decide valuation of company, says Haleon CEO"
description = "Brian McNamara discusses the London Stock Exchange listing of GSK spin-off Haleon, a consumer health business."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=QYxop4AEhCY
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = QYxop4AEhCY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/QYxop4AEhCY/maxresdefault.webp

