[item]
guid = R0psmZflGrc
title = "The recession coming won't be a 'normal' one, but it's coming, strategist says"
description = "Luke Hickmore, investment director at Abrdn, explains why a recession is his base case, and adds that it won't be a "full-blown" one but a consumer recession."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=R0psmZflGrc
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = R0psmZflGrc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/R0psmZflGrc/hqdefault.jpg

