[item]
guid = R8Qvi0wF43k
title = "A 'genuine recession' could be coming to the U.S. in 2023, says economist"
description = "Christiaan Tuntono of Allianz Global Investors gives its forecast for the U.S. Federal Reserve's interest rate hikes and says it'll be facing a difficult situation."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=R8Qvi0wF43k
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = R8Qvi0wF43k.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/R8Qvi0wF43k/maxresdefault.webp

