[item]
guid = RLyduNOKWM8
title = "Jordan's king says he believes a Middle Eastern 'NATO' can be built with like-minded countries"
description = "Jordan's King Abdullah II says he would be "one of the first people that would endorse a Middle East NATO," but the vision of such an alliance must be very clear."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=RLyduNOKWM8
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = RLyduNOKWM8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/RLyduNOKWM8/maxresdefault.webp

