[item]
guid = S0KPU5lN7Sg
title = "Retail pricing environment will evolve over the next few quarters: Wells Fargo"
description = "Chris Carey of Wells Fargo Securities says that while Pepsico can navigate and price consumer staples to their respective markets, strengthening of the U.S. dollar may affect multinational earnings, and increased retailer sensitivity to higher pricing requires close monitoring."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=S0KPU5lN7Sg
category = "News & Politics"
pubdate = Wed, 13 Jul 2022 00:00:00 -0000
enclosure = S0KPU5lN7Sg.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/S0KPU5lN7Sg/maxresdefault.jpg

