[item]
guid = T78fFFyUcZY
title = "It will be months until central banks pause on hiking rates, Barclays' Jean-Paul Jaegers says"
description = "Jean-Paul Jaegers, head of asset allocation at Barclays Wealth & Investments, discusses inflation, which he says is "remains actually quite stubborn and more entrenched in some elements.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=T78fFFyUcZY
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = T78fFFyUcZY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/T78fFFyUcZY/maxresdefault.webp

