[item]
guid = TcauSD0ca4c
title = "Our aspiration is to accelerate growth, says e& CEO"
description = "Shares in UAE telco e& rose more than 5% on Monday after the company formerly known as Etisalat announced a major rebrand and strategic restructure."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=TcauSD0ca4c
category = "News & Politics"
pubdate = Wed, 29 Jun 2022 00:00:00 -0000
enclosure = TcauSD0ca4c.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/TcauSD0ca4c/hqdefault.jpg

