[item]
guid = tKovZNVLRXQ
title = "Prince Turki: America needs to engage with the kingdom in order to stabilize oil prices"
description = "Prince Turki Al-Faisal, Saudi Arabia’s former intelligence chief and former ambassador to the United States, tells CNBC that America needs to engage with the kingdom in order to stabilize oil prices, ahead of President Biden's trip to Saudi Arabia."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=tKovZNVLRXQ
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = tKovZNVLRXQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/tKovZNVLRXQ/maxresdefault.jpg

