[item]
guid = u0dQnI2-fhI
title = "Housing in many Asian cities is expensive regardless of what the inflation rate is, says consultancy"
description = "Renee McGowan of Mercer discusses the results of its Cost of Living survey."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=u0dQnI2-fhI
category = "News & Politics"
pubdate = Thu, 30 Jun 2022 00:00:00 -0000
enclosure = u0dQnI2-fhI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/u0dQnI2-fhI/maxresdefault.webp

