[item]
guid = U0fV4QAbPIQ
title = "Watch Saudi Arabia’s Climate Envoy Adel Al-Jubeir Full Interview"
description = "Adel Al-Jubeir, Saudi Arabia’s Minister of State for Foreign Affairs and Envoy for Climate Affairs speaks to CNBC's Hadley Gamble in Jeddah about Saudi Arabia’s climate policy, oil production and President Biden's visit to the Kingdom.\n\n_________________________________________________\n\nSubscribe to CNBC International TV: http://cnb.cx/2wAkfMv\n \nSubscribe to CNBC International: http://cnb.cx/2gft82z\n\nLike our Facebook page\nhttps://www.facebook.com/cnbcinternational\n\nFollow us on Instagram\nhttps://www.instagram.com/cnbcinternational/\n\nFollow us on Twitter\nhttps://twitter.com/cnbci"
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=U0fV4QAbPIQ
category = "News & Politics"
pubdate = Sat, 16 Jul 2022 00:00:00 -0000
enclosure = U0fV4QAbPIQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/U0fV4QAbPIQ/maxresdefault.webp

