[item]
guid = upsEYNV30xQ
title = "I've put some of my own money into emerging markets, says economist"
description = "Charlie Robertson, author of "The Time-Travelling Economist" and global chief economist at Renaissance Capital, discusses the outlook for emerging markets."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=upsEYNV30xQ
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = upsEYNV30xQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/upsEYNV30xQ/maxresdefault.webp

