[item]
guid = usNvJNy3UG8
title = "The stage is set for more stability in tech stocks, says investor"
description = "Daniel Boardman-Weston, CEO & CIO at BRI Wealth Management, says that tech stocks — hard-hit in the recent market sell-off — are poised to stabilize over the coming months, with top-performing companies proving resilient."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=usNvJNy3UG8
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = usNvJNy3UG8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/usNvJNy3UG8/maxresdefault.webp

