[item]
guid = vAovpyvmmQg
title = "Norges Bank governor discusses Norway's biggest rate hike in 20 years"
description = "Ida Wolden Bache, governor at the Norges Bank, speaks to CNBC's Julianna Tatelbaum."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=vAovpyvmmQg
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = vAovpyvmmQg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/vAovpyvmmQg/maxresdefault.jpg

