[item]
guid = vFnZ5iDU_ZY
title = "India's Reliance Industries is going to do well, says stock broking firm"
description = "Shrikant Chouhan of Kotak Securities says the multinational conglomerate is "very aggressive" in its digitalization efforts."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=vFnZ5iDU_ZY
category = "News & Politics"
pubdate = Mon, 27 Jun 2022 00:00:00 -0000
enclosure = vFnZ5iDU_ZY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/vFnZ5iDU_ZY/maxresdefault.webp

