[item]
guid = VJP8ZtijeQI
title = "Biden's visit to Saudi Arabia unlikely to result in a triumph for either party, oil analyst says"
description = "Neil Atkinson, independent oil analyst, discusses diplomatic relations between the U.S. and Saudi Arabia and how this is likely to influence energy markets."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=VJP8ZtijeQI
category = "News & Politics"
pubdate = Thu, 30 Jun 2022 00:00:00 -0000
enclosure = VJP8ZtijeQI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/VJP8ZtijeQI/maxresdefault.webp

