[item]
guid = Vmw5deImGd0
title = "Food inflation from the Russia-Ukraine war could last till 2024, says food and agriculture firm"
description = "Sunny Verghese, CEO of Olam Group, says it's difficult to predict how much more food prices will increase."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=Vmw5deImGd0
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = Vmw5deImGd0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/Vmw5deImGd0/hqdefault.jpg

