[item]
guid = vpiE5j-nBuw
title = "How tapping into this ancient Japanese concept could help you figure out your calling"
description = "When it comes to finding a career, the generally accepted advice is to look for something you enjoy and are good at.\n\nHowever, Alex Liu, managing partner and chairman at management consulting firm Kearney, took it one step further.\n\n“There’s this ancient Japanese concept called ‘ikigai,’ where you’re trying to balance what you’re passionate about, versus what you can get paid for, and what the world needs and what you’re good at,” Liu told CNBC “Make It.”\n\nLiu said that it’s very easy to focus too heavily on just one or two of these factors, which could prevent you from finding the right work for you.\n\nHowever, he believes this principle helped him to not only find his career but also his calling.\n\n“I’m in a profession where I’m coaching companies and teams to reach their full potential. So, in some sense, I found my own ikigai by helping other people reach their full potential.”\n\nThis is just one of five of Alex Liu’s biggest lessons. Watch the video above for more.\n\n---\n\nSubscribe to CNBC International TV: http://cnb.cx/2wAkfMv\n \nSubscribe to CNBC International: http://cnb.cx/2gft82z\n\nLike our Facebook page\nhttps://www.facebook.com/cnbcinternational\n\nFollow us on Instagram\nhttps://www.instagram.com/cnbcinternational/\n\nFollow us on Twitter\nhttps://twitter.com/cnbci"
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=vpiE5j-nBuw
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = vpiE5j-nBuw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/vpiE5j-nBuw/hqdefault.jpg

