[item]
guid = W3i4Ja3b6v8
title = "South Korean defense firm says meeting demand has been difficult because of rising costs"
description = "Richard Cho of Hanwha Defense says supply chain disruptions and rising costs have been hampering the company's activities "in many ways.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=W3i4Ja3b6v8
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = W3i4Ja3b6v8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/W3i4Ja3b6v8/maxresdefault.jpg

