[item]
guid = W8wZkrqU6cc
title = "Full Interview: Prince Turki Al-Faisal on President Biden's Trip to the Kingdom"
description = "Prince Turki Al-Faisal, Saudi Arabia’s former intelligence chief and former Ambassador to the United States speaks to CNBC's Hadley Gamble in Jeddah ahead of President Biden's visit to the Kingdom.\n\n_______________________\n\nSubscribe to CNBC International TV: http://cnb.cx/2wAkfMv\n \nSubscribe to CNBC International: http://cnb.cx/2gft82z\n\nLike our Facebook page\nhttps://www.facebook.com/cnbcinternational\n\nFollow us on Instagram\nhttps://www.instagram.com/cnbcinternational/\n\nFollow us on Twitter\nhttps://twitter.com/cnbci"
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=W8wZkrqU6cc
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = W8wZkrqU6cc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/W8wZkrqU6cc/maxresdefault.webp

