[item]
guid = WBnFLJSUFTw
title = "Europe is growing increasingly worried about a total shutdown of Russian gas"
description = "CNBC's Silvia Amaro speaks to diplomats and policymakers at the European Council in Brussels, as fears grow about the region's future gas supplies from Russia."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=WBnFLJSUFTw
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = WBnFLJSUFTw.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/WBnFLJSUFTw/hqdefault.jpg

