[item]
guid = xME--3pWzTY
title = "Putin's ambitions go beyond occupying Ukrainian territory, says former German ambassador"
description = "Rudiger von Fritsch of Berlin Global Advisors, formerly German ambassador to Russia, discusses the European Union's decision to grant Ukraine and Moldova candidate status."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=xME--3pWzTY
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = xME--3pWzTY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/xME--3pWzTY/maxresdefault.webp

