[item]
guid = Xy20EBdd91E
title = "Dassault Systemes CEO discusses it's second quarter revenue"
description = "Bernard Charles, CEO of Dassault Systemes, says the company has a "secret sauce.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=Xy20EBdd91E
category = "News & Politics"
pubdate = Tue, 26 Jul 2022 00:00:00 -0000
enclosure = Xy20EBdd91E.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/Xy20EBdd91E/maxresdefault.webp

