[item]
guid = XYzfGWA8qhw
title = "There's a tremendous number of exciting companies coming out of Southeast Asia, says NYSE"
description = "John Tuttle of the New York Stock Exchange discusses its collaboration with the Singapore Exchange and says there are lots of global capital flows going into the region."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=XYzfGWA8qhw
category = "News & Politics"
pubdate = Tue, 26 Jul 2022 00:00:00 -0000
enclosure = XYzfGWA8qhw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/XYzfGWA8qhw/hqdefault.jpg

