[item]
guid = y5ZC_5dVqNA
title = "If we're not already in a recession we're about to be, says wealth management firm"
description = "Michael Yoshikami, founder and CEO of Destination Wealth Management, says there's "lots of uncertainty" over what the U.S. Federal Reserve is going to do."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=y5ZC_5dVqNA
category = "News & Politics"
pubdate = Thu, 30 Jun 2022 00:00:00 -0000
enclosure = y5ZC_5dVqNA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/y5ZC_5dVqNA/hqdefault.jpg

