[item]
guid = ycu_wItnvqs
title = "Fintech is seeing 'healthy' pullback after an 'exuberant' 2 years, SumUp CEO says"
description = "Marc-Alexander Christ, CEO and co-founder of SumUp, discusses the payment company's latest funding round and falling valuations in fintech."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=ycu_wItnvqs
category = "News & Politics"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = ycu_wItnvqs.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/ycu_wItnvqs/maxresdefault.webp

