[item]
guid = ydn_t5Mm4x4
title = "Analyst explains why Ryanair has been doing better than many airlines"
description = "John Grant of OAG discusses Ryanair's latest earnings and challenges in the airline industry."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=ydn_t5Mm4x4
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = ydn_t5Mm4x4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ydn_t5Mm4x4/maxresdefault.jpg

