[item]
guid = yFS49VY6x70
title = "Draghi's departure is the greatest loss for Italy and Europe, economist says"
description = "Silvia Ardagna, chief economist at Barclays, said Draghi's departure would be the greatest loss for Italy and Europe."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=yFS49VY6x70
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = yFS49VY6x70.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/yFS49VY6x70/maxresdefault.jpg

