[item]
guid = ypHw9JyrWLk
title = "Monkeypox outbreak is 'not another Covid,' says doctor"
description = "Andrew Freedman of Cardiff University Medical School says the risk to the general public "remains very low.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=ypHw9JyrWLk
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = ypHw9JyrWLk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ypHw9JyrWLk/maxresdefault.jpg

