[item]
guid = ySDM03dji3g
title = "The devil is in the details, analyst says of UN-backed grain deal between Russia and Ukraine"
description = "Andrew Whitelaw of Thomas Elder Markets says it's a "good sign of some thawing of relations, but how far it will go is the issue.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=ySDM03dji3g
category = "News & Politics"
pubdate = Mon, 25 Jul 2022 00:00:00 -0000
enclosure = ySDM03dji3g.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ySDM03dji3g/maxresdefault.jpg

