[item]
guid = yZrDJx5DaFs
title = "Lack of assistance package for Lebanon after Jeddah summit is disappointing, minister says"
description = "Amin Salam, economy and trade minister of Lebanon, says the lack of an assistance package for Lebanon after the Jeddah summit is "disappointing.""
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=yZrDJx5DaFs
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = yZrDJx5DaFs.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/yZrDJx5DaFs/hqdefault.jpg

