[item]
guid = ZDFswu2iVWI
title = "Patrice Evra on dealing with abuse and toxic masculinity"
description = "Former French international and Manchester United soccer player, Patrice Evra, tells CNBC's Dan Murphy why he decided to speak about being sexually abused as a child, the emotional impact and why he's now using his platform for good."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=ZDFswu2iVWI
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = ZDFswu2iVWI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ZDFswu2iVWI/hqdefault.jpg

