[item]
guid = zJxtd7C45Bo
title = "Roche CEO on pharma business: 'We have one of the strongest pipelines in the industry'"
description = "Severin Schwan, CEO of Roche, discusses the company's strength in its pharma business amid the company's half-year results and the announcement that its head of diagnostics division, Thomas Schinecker, will take the position as chief executive in the coming year."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=zJxtd7C45Bo
category = "News & Politics"
pubdate = Thu, 21 Jul 2022 00:00:00 -0000
enclosure = zJxtd7C45Bo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/zJxtd7C45Bo/maxresdefault.jpg

