[item]
guid = ZqlADVJhxf4
title = "Possibility of Italian election in the fall should not be ruled out, says professor"
description = "Giovanni Orsina, professor of contemporary history and director of the School of Government at Luiss-Guido Carli University, discusses the Italian president's refusal to accept Prime Minister Mario Draghi's resignation."
author = CNBC International TV
source = https://www.youtube.com/channel/UCF8HUTbUwPKh2Q-KpGOCVGw
link = https://www.youtube.com/watch?v=ZqlADVJhxf4
category = "News & Politics"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = ZqlADVJhxf4.mp4

[item "itunes"]
image = https://i.ytimg.com/vi/ZqlADVJhxf4/maxresdefault.jpg

